spring:
  main:
    allow-bean-definition-overriding: true
    
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-flash
          temperature: 0.7

  vectorstore:
    redis:
      index-name: spring_ai_index
      initialize-schema: true
      prefix: "doc:"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunxu_ai?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.example.yunxu_ai: debug
server:
  port: 8080
